---
title: "dirich_multinom"
author: "Yifan Duan"
date: "2024-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(brms)
library(DirichletReg)

count_df

count_df_wide <- as.data.frame(count_df) |> 
    pivot_wider(names_from = celltype, values_from = count)

count_df_wide
```

```{r dirichlet eval=F}
# CI estimate not working 
dirich_data <- count_df_wide
dirich_data$cellCounts <- DR_data(dirich_data |> dplyr::select(-c(condition, sample)))
fit1 <- DirichReg(cellCounts ~ condition, dirich_data)
s = summary(fit1)

rv = s$coef.mat
rv = rv[rownames(rv)!="(Intercept)",]

rv = data.frame(rv)

rv$celltype = as.factor(colnames(dirich_data |> dplyr::select(-c(condition, sample, cellCounts))))
rv$sig_stars = gtools::stars.pval(rv$Pr...z..)
rv$odds = exp(rv$Estimate)

rv = fixef(fit1, summary = T, probs = c(0.005, 0.025, 0.05, 0.15, 0.25, 0.75, 0.85, 0.95, 0.975, 0.995)) %>% data.frame()

rv$odds_95hi = exp(rv$Q97.5)
rv$odds_95lo = exp(rv$Q2.5)
# Combine lower and upper confidence intervals into a data frame
ci_df <- data.frame(
  celltype = rv$celltype,
  lower_CI = lower_ci,
  upper_CI = upper_ci,
  method = as.factor("dirichlet")
)
```


```{r dirichlet-multinomial}
library(stringr)
dirich_data <- count_df_wide
dirich_data$cellCounts <- DR_data(dirich_data |> dplyr::select(-c(condition, sample)))

fit_bayes <- brm(cellCounts ~ condition, dirich_data, dirichlet(refcat = "Mono"), cores = 1, chains = 4)
rv = fixef(fit_bayes, summary = T, probs = c(0.005, 0.025, 0.05, 0.15, 0.25, 0.75, 0.85, 0.95, 0.975, 0.995)) %>% data.frame()
rv$cell = rownames(rv)
rownames(rv) = NULL
rv = rv %>% filter(!grepl("_Intercept", rv$cell))
rv$cell = gsub("mu", "", rv$cell)
rv$contrast = str_split_fixed(rv$cell, "_", 2)[, 2]
rv$cell = str_split_fixed(rv$cell, "_", 2)[, 1]
rv = rv %>% mutate(sig_label = case_when(
    sign(Q0.5) == sign(Q99.5) ~ "PI_99",
    sign(Q2.5) == sign(Q97.5) ~ "PI_95",
    sign(Q5) == sign(Q95) ~ "PI_90",
    sign(Q15) == sign(Q85) ~ "PI_80", 
    TRUE ~ "NS"
))

ci_df <- data.frame(
  celltype = rv$cell,
  lower_CI = exp(rv$Q2.5),
  upper_CI = exp(rv$Q97.5),
  method = as.factor("dirichlet-multinomial")
)

plotCellTypeProps(clusters=propeller_data$celltype, sample=propeller_data$condition) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

