---
title: "propeller"
author: "Yifan Duan"
date: "2023-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(speckle)
library(limma)
library(ggplot2)

# Get some example data which has two groups, three cell types and two 
# biological replicates in each group
cell_info <- speckle_example_data()
head(cell_info)

# Run propeller testing for cell type proportion differences between the two 
# groups
propeller(clusters = cell_info$clusters, sample = cell_info$samples, 
group = cell_info$group)

# Plot cell type proportions
plotCellTypeProps(clusters=cell_info$clusters, sample=cell_info$samples)
```


```{r}
# Assuming so2_control is a Seurat object with timepoint 0 cells
so2_control <- subset(so2, subset = timepoint == 0)

# Sample a set of cell names without replacement
so2_non_control_cells <- sample(Cells(so2_control), size = length(Cells(so2_control)) / 2, replace = F)

# Update the timepoint in the metadata for these cells
so2_control@meta.data[so2_non_control_cells, "timepoint"] <- 1
dim(so2)
dim(so2_control)
table(so2_control$timepoint)

so2_control$sample <- paste0(ifelse(so2_control$timepoint == 0, "c", "nc"), so2_control$mouse)
table(so2_control$sample)
```


```{r}

propeller(clusters = so2_control$celltype, sample = so2_control$sample, 
group = so2_control$timepoint)

# Plot cell type proportions
plotCellTypeProps(clusters = so2_control$celltype, sample = so2_control$sample)
plotCellTypeProps(clusters = so2_control$celltype, sample = so2_control$timepoint)

```

```{r}
# Assuming so2_control is a Seurat object with timepoint 0 cells
#so2_control <- subset(so2, subset = timepoint == 0)

N <- 10  # The number of bootstrap samples you want to create.
propeller_results <- vector("list", N)

# Loop through N times to create N bootstrap samples and corresponding plots.
for (i in 1:N) {
  # Generate a sample of non-control cells.
  so2_non_control_cells <- sample(Cells(so2_control), size = length(Cells(so2_control)) / 2, replace = FALSE)
  
  # Create a copy of so2_control to modify.
  temp_so2_control <- so2_control
  
  # Modify the timepoint for the non-control cells in this copy.
  temp_so2_control@meta.data[so2_non_control_cells, "timepoint"] <- 1
  
  # Label the cells as 'control' (c) or 'non-control' (nc) based on the new timepoint.
  temp_so2_control$sample <- paste0(ifelse(temp_so2_control@meta.data$timepoint == 0, "c", "nc"), temp_so2_control@meta.data$mouse)

  propeller_results[[i]] <- propeller(clusters = temp_so2_control$celltype, 
                                      sample = temp_so2_control$sample, 
                                      group = temp_so2_control$timepoint)
}

propeller_results
```

